### ISSUE TITLE
roms: make target 48.ROM not included in all

### ISSUE THREAD

**Issue by rickard-von-essen** [alvieboy/ZXInterfaceZ#11]
`48.ROM` isn't included in the `all` target and depend on `zx-spectrum-rom.asm` which is missing.

**Comment by alvieboy** [comment]
This was on purpose, since that target is used to build the original ROM for the Spectrum 48K, which is copyrighted by Amstrad. I undestrand that Amstrad does allow ROM to be distributed as part of an emulator, but we are not an emulator (and we don't actually need that ROM).

I'll remove the target not to confuse people.

**Comment by rickard-von-essen** [comment]
👍 makes sense. Remove it or add a comment.
